# 
name: ECS Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: demo
  CLUSTER_NAME: demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build --no-cache -t demo:latest .

      - name: Tag Docker image as latest
        run: |
          docker tag demo:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

      - name: Push Docker image as latest
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

      - name: Register new task definition revision
        id: register-task-definition
        run: |
          aws ecs register-task-definition \
            --family demo-1 \
            --container-definitions '[
              {
                "name": "demo",
                "image": "'"${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest"'",
                "essential": true,
                "memory": 2048,
                "cpu": 1024
              }
            ]' \
            --region ${{ env.AWS_REGION }} \
            | jq -r '.taskDefinition.taskDefinitionArn' > task_definition_arn.txt

      - name: Run ECS Task with the new image
        run: |
          NEW_TASK_DEFINITION_ARN=$(cat task_definition_arn.txt)
          aws ecs run-task \
            --cluster ${{ env.CLUSTER_NAME }} \
            --launch-type EC2 \
            --task-definition $NEW_TASK_DEFINITION_ARN \
            --count 1 \
            --region ${{ env.AWS_REGION }}
